#!/bin/bash
# Get ng2 module from github

if [ -z $APPNAME ]; then
  echo "APPNAME is empty. Set APPNAME"
else
  cd /home/$APPNAME/app/modules
  sudo git clone https://github.com/mpduffey/$1
  sudo chown ec2-user:ec2-user -R $1
  sudo chmod 755 -R $1
 fi