#!/bin/bash
# Get ng2 module from github

if [ -z $APPNAME ]; then
  echo "APPNAME is empty. Set APPNAME"
else
	cd /home/$APPNAME
	git-status-and-push
	
	cd /home/$APPNAME/css
	git-status-and-push
	
	cd /home/$APPNAME/app/modules/$dir
	for D in *; do
		if [ -d "${D}" ]; then
			printf "\n--------------------------------------------------\nCurrent git status for '$D'\n--------------------------------------------------\n"
			cd $D
			git-status-and-push
			cd ..
		fi
	done
fi