#!/bin/bash
# Git Pull all Modules

cd /var/www/html
printf "\n--------------------------------------------------\nUpdating '$APPNAME'\n--------------------------------------------------\n"
git fetch --all
git reset --hard origin/master

cd /var/www/html/css
printf "\n--------------------------------------------------\nUpdating 'css'\n--------------------------------------------------\n"
git fetch --all
git reset --hard origin/master

cd /var/www/html/app/modules
for D in *; do
	if [ -d "${D}" ]; then
		printf "\n--------------------------------------------------\nUpdating '$D'\n--------------------------------------------------\n"
		cd $D
		git fetch --all
		git reset --hard origin/master
		cd ..
	fi
done