#!/bin/bash
# Launch EC-2 instance

cd /home/ec2-user
git config --global user.name "Mike Duffey"
git config --global user.email "mpduffey@gmail.com"
git config --global credential.helper store
sudo curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -
sudo yum install -y gcc-c++ make
sudo yum install -y nodejs
sudo npm install npm -g
sudo yum install autoconf autoconf autoconf-archive automake ncurses-devel curl-devel erlang-asn1 erlang-erts erlang-eunit erlang-os_mon erlang-xmerl help2man js-devel libicu-devel libtool perl-Test-Harness gcc-c++
sudo wget http://www.erlang.org/download/otp_src_R14B01.tar.gz
sudo tar -xvf otp_src_R14B01.tar.gz
cd otp_src_R14B01
sudo ./configure
sudo make && sudo make install
sudo yum install cvs zip gcc-c++ glib2-devel gtk2-devel fontconfig-devel libnotify-devel libIDL-devel alsa-lib-devel libXt-devel freetype-devel pkgconfig dbus-glib-devel curl-devel autoconf213 xorg-x11-proto-devel libX11-devel libXau-devel libXext-devel wireless-tools-devel glibc-static libstdc++-static yasm mesa-libGL-devel esound-libs esound-devel ccache mercurial
sudo curl -L -O http://ftp.mozilla.org/pub/mozilla.org/js/js185-1.0.0.tar.gz
sudo tar xvf js185-1.0.0.tar.gz
cd js-1.8.5/js/src
autoconf-2.13
sudo ./configure
sudo make && sudo make install
sudo wget http://mirror.tcpdiag.net/apache/couchdb/source/1.6.1/apache-couchdb-1.6.1.tar.gz
sudo tar -xvf apache-couchdb-1.6.1.tar.gz
cd apache-couchdb-1.6.1
sudo ./configure --with-erlang=/usr/local/lib/erlang/usr/include
sudo make && sudo make install

# Set file and folder owners and permissions
sudo chmod 777 /lost+found
sudo chmod 777 /root
sudo chmod 777 /usr/local/etc/couchdb
sudo chmod 777 /usr/local/etc/couchdb/local.ini
sudo chmod 777 /usr/local/var/lib/couchdb
sudo chmod 777 /usr/local/var/run/couchdb
sudo chmod -R 777 /usr/local/var/log/couchdb
sudo chown ec2-user -R /home/ec2-user/bin
sudo chmod 775 -R home/ec2-user/bin

sudo yum install mysql mysql-server
sudo service mysqld start
sudo npm install forever -g
sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to 3000
sudo npm install -g yo generator-generator
sudo npm install -g ionic@beta cordova

# 32-bit packages for Android
sudo yum install -y glibc.i686 glibc-devel.i686 libstdc++.i686 zlib-devel.i686 ncurses-devel.i686 libX11-devel.i686 libXrender.i686 libXrandr.i686

# confirm installations
git --version
node -v
npm -v
