#!/bin/bash
# Launch EC-2 instance
# configure git
# install nodejs and npm
# install and start mysql
# install ionic, yeoman, generator-generator, typings and forever

cd /home/ec2-user
git config --global user.name "Mike Duffey"
git config --global user.email "mpduffey@gmail.com"
git config --global credential.helper store
curl --silent --location https://rpm.nodesource.com/setup_6.x | sudo bash -
sudo yum install -y gcc-c++ make nodejs
npm install npm -g -y

mkdir ~/.npm-global
npm config set prefix '~/.npm-global'

export PATH=~/.npm-global/bin:$PATH

sudo yum install mysql mysql-server httpd24 -y
sudo service mysqld start
npm install -g typings forever gulp-cli yo generator-generator ionic@beta cordova sails
npm run typings install

# 32-bit packages for Android
sudo yum install -y glibc.i686 glibc-devel.i686 libstdc++.i686 zlib-devel.i686 ncurses-devel.i686 libX11-devel.i686 libXrender.i686 libXrandr.i686

# confirm installations
git --version
node -v
npm -v