#!/bin/bash
# Launch ng2 app

if [ -z $1 ]; then
	printf "No App Name provided. Please add an app name to the command like 'ng2-app [App Name]'. \n\n"
else
	cd /home
	sudo mkdir $1
	sudo chown ec2-user:ec2-user -R /home/$1
	sudo chmod 2775 -R /home/$1
	cd /home/$1
	git clone https://github.com/angular/quickstart .
	cd $1
	sudo rm -r .git
	curl -u 'mpduffey' https://api.github.com/user/repos -d '{"name": "'$1'"}'
	npm install gulp --save-dev
	npm run typings install
	mkdir app/modules
	touch gulpfile.js
	git init
	git remote add origin https://github.com/mpduffey/$1
	git-push 'v0.0.1'
	mkdir css
	cd css
	git clone https://github.com/mpduffey/ng2-css.git .
	cd /home
	sails new $1-api
fi