#!/bin/bash
# Create Angular 2 module

if [ -z $APPNAME ]; then
  echo "APPNAME is empty. Set APPNAME"
else
  curl -u 'mpduffey' https://api.github.com/user/repos -d '{"name": "'$1'"}'
  cd /home/$APPNAME/app/modules
  git clone https://github.com/mpduffey/$1
  sudo chown ec2-user -R $1
  sudo chmod 2775 -R $1
  cd $1
  sudo npm init -y
  sudo touch $1.ts
  sudo git add .
  sudo git commit -m 'v0.0.0'
  sudo git push origin master
fi