#!/bin/bash
# Launch ng2 app

if [ -z $1 ]; then
	APPNAME="NewApp"
else
	APPNAME=$1
fi

cd /home
sudo git clone https://github.com/angular/quickstart $APPNAME
sudo chown ec2-user -R /home/$APPNAME
sudo chmod 775 -R /home/$APPNAME
cd $APPNAME
sudo rm -r .git
curl -u 'mpduffey' https://api.github.com/user/repos -d '{"name": "'$APPNAME'"}'
sudo npm install
mkdir app/modules
git init
git remote add origin https://github.com/mpduffey/$APPNAME
gitpush 'v0.0.1'
mkdir css
cd css
git clone https://github.com/mpduffey/ng2-css.git .