#!/bin/bash
# Create Angular 2 Model

if [ -z $1 ]; then
	echo 'You must name your model!'
	exit
else
	MODELNAME='$1.model'
	curl -u 'mpduffey' https://api.github.com/user/repos -d '{"name": "'$MODELNAME'"}'
	cd /home/$APPNAME/app/models
	git clone https://github.com/mpduffey/$MODELNAME
	cd $MODELNAME
	npm init -y
	touch $MODELNAME.ts
	git add .
	git commit -m 'v0.0.0'
	git push origin master
fi